name = "genova-ai"
compatibility_date = "2025-01-21"
node_compat = true

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[site]
bucket = ".next"

[env.production]
node_compat = true

# Cloudflare Pages specific settings
pages_build_output_dir = ".next"
