name = "genova-ai"
compatibility_date = "2025-01-21"
node_compat = true

[build]
command = "npm run build"
[build.upload]
format = "service-worker"

[env.production]
node_compat = true

[site]
bucket = ".next"
